apiVersion: v1
kind: Service
metadata:
  name: testapp-metrics-service
  namespace: testapp-metrics
  labels:
    app: testapp-metrics
spec:
  type: LoadBalancer
  selector:
    app: testapp-metrics
  ports:
    - name: http
      port: 80
      targetPort: 8080
