apiVersion: v1
kind: Service
metadata:
  name: testapp-service
  namespace: testapp
  labels:
    app: testapp
spec:
  type: LoadBalancer
  selector:
    app: testapp
  ports:
    - name: http
      port: 80
      targetPort: 5678
